### ISSUE TITLE
hot-restart every time a test is to be executed to improve isolation

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_convenient_test#113]
## What

when executing multiple tests, do a hot-restart before each of them.

this should be an optional feature, since some people may already have good isolation even for e2e tests and do not need this.

## Why

* https://github.com/fzyzcjy/yplusplus/issues/3781#issuecomment-1119547142 (internal link)

## How

- [ ] when user let the manager to execute multiple tests (e.g. "run all"), the manager do "hot restart - please run one test - hot restart - please run one test - ..."
- [ ] the worker smartly only execute *one* test, and skip everything once it finishes *one* test
- [ ] to know which one test to execute, the manager tells the worker "execute the test just next to test named aaaaaa", where aaaaaa is the last reported test
- [ ] when a test report it is "pending -> running", clear every log / rawlog related to it
- [ ] tell the worker *no need to report* Suite info, unless it is running the *first* test in such a series.

## Things to consider

- [x] be careful: all generated *id*s in worker. after a hot restart it will forget it, and then generate duplicate ids! -- #115
- [x] suite info
- [x] log entry
- [x] the video (currently start in setupall, end in teardownall) -- let us support multiple videos. and for each test, it just record one single video. even better, since now the end user directly has one separate video for one test case. --- #125
- [x] CI mode -- since it is hard to get rid of the Manager, and we also want videos (which can only be recorded using a process in *host* machine, since cannot record in the simulator), what about creating a "headless Manager", which is a pure dart process --- #117

**Comment by fzyzcjy** [comment]
maybe similar to implement: #55

**Comment by fzyzcjy** [comment]
shall we record a video for *each* hot restart, or only one video among all tests?

**Comment by fzyzcjy** [comment]
Question: how to merge data from multiple hot-restarts?

just behave as if they come from single hot-restart.

of course, need to be careful about how to react with setupall and teardownall, since that no longer means "really" setup a brand new testing situation, and should not clear all data.

For .bin file, just concat them. nothing special.

**Comment by fzyzcjy** [comment]
firstly, add a "do not report suite info" flag

**Comment by fzyzcjy** [comment]
next: [TODO]

**Comment by fzyzcjy** [comment]
- [ ] add ExecutionMode
- [ ] execute according to ExecutionMode

**Comment by fzyzcjy** [comment]
- [ ] stopping criterion (currently the `NextMatch` will throw if there is nothing more to execute...)

**Comment by fzyzcjy** [comment]
now the proto & worker is done. next: manager

**Comment by fzyzcjy** [comment]
WorkerMode ->

WorkerModeSource + WorkerModeExecutionInfo

**Comment by fzyzcjy** [comment]
rename "WorkerMode" (to be seen by Worker)

**Comment by fzyzcjy** [comment]
- [ ] getter/setter to `isolationMode`

**Comment by fzyzcjy** [comment]
next: implemen _WorkerSuperRunControllerIntegrationTestIsolationMode

**Comment by fzyzcjy** [comment]
- [ ] TODO: _WorkerSuperRunControllerIntegrationTestIsolationMode change state when worker reports something

**Comment by fzyzcjy** [comment]
(will finish this today)

**Comment by fzyzcjy** [comment]
next: clear data at suitable situations

Question: clear what data?
Question: at what time?

**Comment by fzyzcjy** [comment]
done

**Comment by fzyzcjy** [comment]
next: a few other issues
